In [1]:
import pandas as pd
from data_extraction import read_raw_files
from data_processing import *
from model_extraction import load_model

In [2]:
df = read_raw_files()

In [3]:
df1 = read_raw_files(n_files=37)
df1.label.unique()

array(['male_fearful', 'female_angry', 'female_calm', 'female_sad',
       'male_angry', 'male_sad', 'male_happy', 'male_calm',
       'female_fearful', 'female_happy'], dtype=object)

In [4]:
l = [i for i in range(100)]
l[0:-1:10]

[0, 10, 20, 30, 40, 50, 60, 70, 80, 90]

In [5]:
df1.label.unique()

array(['male_fearful', 'female_angry', 'female_calm', 'female_sad',
       'male_angry', 'male_sad', 'male_happy', 'male_calm',
       'female_fearful', 'female_happy'], dtype=object)

In [6]:
df1.head()

label          0          1          2          3          4  \
21  male_fearful -61.087368 -61.579323 -61.580788 -61.288128 -61.081142   
20  female_angry -46.138206 -46.138206 -46.138206 -46.138206 -46.138206   
4    female_calm -80.365234 -80.365234 -80.365234 -80.365234 -80.365234   
10    female_sad -66.503899 -66.503899 -66.503899 -66.503899 -66.503899   
14    female_sad -52.077213 -50.420513 -46.801186 -44.139469 -43.354549   

            5          6          7          8  ...        206        207  \
21 -60.591736 -59.902363 -59.477730 -60.251350  ... -56.197136 -53.662144   
20 -46.138206 -46.138206 -46.138206 -46.138206  ... -26.907887 -29.334385   
4  -80.365234 -80.365234 -80.365234 -80.365234  ... -67.552673 -71.822395   
10 -66.503899 -66.503899 -66.503899 -66.503899  ... -52.475349 -52.229416   
14 -43.309910 -44.002316 -44.234722 -43.001114  ... -51.283489 -50.625809   

          208        209        210        211        212        213  \
21 -53.636868 -55.863472 -56.614315 -56.009319 -54.970852 -54.317688   
20 -30.515127 -30.826090 -31.697905 -31.302111 -33.171894 -34.666664   
4  -67.615128 -66.810692 -68.890640 -67.609535 -65.278763 -65.307877   
10 -54.141418 -56.338928 -55.589706 -54.620144 -54.073235 -52.911312   
14 -52.064594 -53.155735 -51.934185 -51.763165 -52.547237 -50.747623   

          214        215  
21 -56.101189 -56.822609  
20 -32.116180 -34.401711  
4  -66.985580 -69.478569  
10 -54.112370 -56.278381  
14 -48.736938 -46.721615  

[5 rows x 217 columns]

In [7]:
df.head()

label          0          1          2          3          4  \
938    male_fearful -41.033859 -43.473728 -44.571995 -45.404984 -45.459835   
634      male_angry -52.434673 -51.535824 -53.196323 -52.245152 -51.765457   
851  female_fearful -59.889175 -59.889175 -59.889175 -59.889175 -59.889175   
166       male_calm -64.836502 -64.743034 -64.995651 -64.995651 -64.995651   
269    female_happy -53.769722 -53.081631 -53.512714 -53.126194 -54.014610   

             5          6          7          8  ...        206        207  \
938 -45.979374 -46.638767 -45.706509 -45.103676  ... -37.025810 -36.153347   
634 -49.566086 -49.411064 -48.564835 -49.487381  ... -47.406448 -45.762714   
851 -59.889175 -59.889175 -59.889175 -59.889175  ... -51.419533 -51.556118   
166 -64.995651 -64.995651 -64.995651 -64.995651  ... -24.830919 -25.499186   
269 -54.318237 -55.030159 -56.599483 -56.698189  ... -57.683159 -55.310097   

           208        209        210        211        212        213  \
938 -35.001041 -35.734093 -34.929306 -33.435040 -32.902012 -32.227551   
634 -46.912212 -50.075729 -48.734596 -49.856754 -50.899651 -50.184677   
851 -52.688267 -51.571003 -51.334293 -52.267338 -53.137516 -53.039246   
166 -25.857328 -25.423267 -25.191694 -26.446756 -27.948254 -27.422558   
269 -55.652992 -53.802818 -52.698906 -51.941059 -51.811016 -53.279785   

           214        215  
938 -32.627934 -30.547537  
634 -47.826580 -45.630180  
851 -51.566658 -51.257515  
166 -25.835690 -23.983660  
269 -55.381798 -58.272831  

[5 rows x 217 columns]

In [8]:
X_train, X_test, y_train, y_test, lb = split_df(df, transform=True)

In [9]:
X_train

array([[[-57.43790436],
        [-57.43790436],
        [-57.43790436],
        ...,
        [-36.72548676],
        [-36.80500793],
        [-38.34606171]],

       [[-65.24334717],
        [-65.24334717],
        [-65.24334717],
        ...,
        [-58.61990738],
        [-60.0683136 ],
        [-57.35060501]],

       [[-51.82197571],
        [-54.55896759],
        [-54.59420013],
        ...,
        [-24.89920235],
        [-21.36425972],
        [-15.93506718]],

       ...,

       [[-65.01216888],
        [-62.33224869],
        [-65.14536285],
        ...,
        [-67.94847107],
        [-71.52256775],
        [-76.50849915]],

       [[-61.11098099],
        [-60.010746  ],
        [-61.09980011],
        ...,
        [-24.66411591],
        [-22.25074387],
        [-19.15155983]],

       [[-64.89439392],
        [-64.89439392],
        [-64.89439392],
        ...,
        [-56.86887741],
        [-60.20554733],
        [-62.32952499]]])

In [10]:
model = load_model(name='best_model')

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_7 (Conv1D)            (None, 216, 128)          768       
_________________________________________________________________
activation_8 (Activation)    (None, 216, 128)          0         
_________________________________________________________________
conv1d_8 (Conv1D)            (None, 216, 128)          82048     
_________________________________________________________________
activation_9 (Activation)    (None, 216, 128)          0         
_________________________________________________________________
dropout_3 (Dropout)          (None, 216, 128)          0         
_________________________________________________________________
max_pooling1d_2 (MaxPooling1 (None, 27, 128)           0         
_________________________________________________________________
conv1d_9 (Conv1D)            (None, 27, 128)           8

In [35]:
import keras

opt = keras.optimizers.RMSprop(lr=0.00001, decay=1e-6)
#####################
X_train, X_test, y_train, y_test, _ = split_df(df, transform=True)
# evaluate loaded model on test data
model.compile(loss='categorical_crossentropy', optimizer=opt, metrics=['accuracy'])
score = model.evaluate(X_test, y_test, verbose=0)
print("%s: %.2f%%" % (model.metrics_names[1], score[1]*100))

accuracy: 91.67%


In [17]:
import librosa
data, sampling_rate = librosa.load('VoiceExamples/Veronica_Stepanova.wav')

In [18]:
X, sample_rate = librosa.load('VoiceExamples/bastard.wav', res_type='kaiser_fast',duration=2.5,sr=22050*2,offset=0.5)
sample_rate = np.array(sample_rate)
mfccs = np.mean(librosa.feature.mfcc(y=X, sr=sample_rate, n_mfcc=13),axis=0)
featurelive = mfccs
livedf2 = featurelive

In [19]:
livedf2= pd.DataFrame(data=livedf2)

In [20]:
livedf2 = livedf2.stack().to_frame().T

In [21]:
livedf2

0          1         2          3          4          5          6    \
           0          0         0          0          0          0          0   
0 -31.016605 -29.984844 -32.55986 -33.465763 -32.890621 -31.157042 -30.686033   

        7         8          9    ...       206        207        208  \
          0         0          0  ...         0          0          0   
0 -29.89053 -30.73344 -30.029217  ... -36.48138 -34.379936 -33.063076   

         209        210        211        212        213        214        215  
           0          0          0          0          0          0          0  
0 -31.214642 -30.910337 -32.996284 -31.520571 -28.852793 -26.045702 -21.808651  

[1 rows x 216 columns]

In [22]:
twodim= np.expand_dims(livedf2, axis=2)

In [23]:
livepreds = model.predict(twodim, 
                         batch_size=32, 
                         verbose=1)

1/1 [==============================] - 0s 1ms/step


In [24]:
livepreds

array([[6.88976143e-05, 1.18949136e-03, 2.54648216e-02, 3.02731190e-02,
        9.42987800e-01, 5.14863725e-14, 1.12755284e-10, 5.37848518e-06,
        1.57825625e-07, 1.03073235e-05]], dtype=float32)

In [25]:
livepreds1=livepreds.argmax(axis=1)

In [26]:
livepreds1

array([4], dtype=int64)

In [27]:
liveabc = livepreds1.astype(int).flatten()

In [28]:
livepredictions = (lb.inverse_transform((liveabc)))
livepredictions

array(['female_sad'], dtype=object)

In [29]:
from voice_recognition import Recognizer

In [30]:
rec = Recognizer()

In [34]:
rec.recognize(['VoiceExamples/Veronica_Stepanova.wav', 'VoiceExamples/calm_Daria.wav', 'VoiceExamples/angry_man.wav',
               'VoiceExamples/sad_Vladimir.wav'], start_from=0.42)

1/1 [==============================] - 0s 1ms/step


{'VoiceExamples/Veronica_Stepanova.wav': 'female_sad',
 'VoiceExamples/calm_Daria.wav': 'female_calm',
 'VoiceExamples/angry_man.wav': 'male_angry',
 'VoiceExamples/sad_Vladimir.wav': 'male_sad'}

In [ ]:
from voice_recognition import Recognizer
rec = Recognizer()
rec.recognize(['VoiceExamples/angry_man.wav',\
               'VoiceExamples/sad_Vladimir.wav',\
               'VoiceExamples/calm_Daria.wav'], start_from=0.5)

In [ ]:
rec.